### ISSUE TITLE
[Feature] Barcode

### ISSUE THREAD

**Issue by fernandodeveloper** [barisatalay/thermalprinterhelper#2]
Its possible implements barcode to send to printer?

**Comment by barisatalay** [comment]
Dear Fernando,

I think its possible, but Im not tried any time.
What is "Barcode"?
If barcode are bitmap just use this method : "printImage"

Best Regards,

**Comment by fernandodeveloper** [comment]
Barcode is same code in EAN13, DUN etc. The printers have commands specific for print barcode in ESC/POS

**Comment by barisatalay** [comment]
You must convert your "EAN13,DUN etc. " to bitmap, because  we only support text,byte,bitmap
